// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKAc7T0MkR-9rlaRKt_lgLY-U2T9xi8oE',
    appId: '1:868939235910:web:5383a09afc39dd2044c047',
    messagingSenderId: '868939235910',
    projectId: 'attendify-38452',
    authDomain: 'attendify-38452.firebaseapp.com',
    storageBucket: 'attendify-38452.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3ofBL9pPk5OD7dLhz9GNq1E5_gBOLso',
    appId: '1:868939235910:android:6851ae0b60d1801f44c047',
    messagingSenderId: '868939235910',
    projectId: 'attendify-38452',
    storageBucket: 'attendify-38452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWdzNxzJlzrwlkZZywPbgdwZGM73PA5o',
    appId: '1:868939235910:ios:cbde18aaccbcdf2444c047',
    messagingSenderId: '868939235910',
    projectId: 'attendify-38452',
    storageBucket: 'attendify-38452.firebasestorage.app',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWdzNxzJlzrwlkZZywPbgdwZGM73PA5o',
    appId: '1:868939235910:ios:cbde18aaccbcdf2444c047',
    messagingSenderId: '868939235910',
    projectId: 'attendify-38452',
    storageBucket: 'attendify-38452.firebasestorage.app',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKAc7T0MkR-9rlaRKt_lgLY-U2T9xi8oE',
    appId: '1:868939235910:web:d65d663fa5fd498944c047',
    messagingSenderId: '868939235910',
    projectId: 'attendify-38452',
    authDomain: 'attendify-38452.firebaseapp.com',
    storageBucket: 'attendify-38452.firebasestorage.app',
  );
}
